server:
  port: 9797

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xcx?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    #    password: Hzs121914.
    password: hzs121914
    #    url: jdbc:mysql://47.103.4.57:3306/hzsshopping?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wx.xcz.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com:
      wx:
        xcx:
          mapper: debug
  file: src\main\resources\logger\myLog.log

